import * as products from "../assets/products";

var i = 0;

export var productsData = [
  {
    "index": i++,
    "tags": ['New'],
    "categories": ['headphone'],
    "discount": 0,
    "img_url": products.headphone1,
    "name": "Red Beats by Dr. Dre wireless headphones",
    "brand": "Dr.Dre",
    "model": "",
    "stars": 4,
    "reviews": 300,
    "price_usd": 325,
    "ship_to_country": "Egypt"
  },
  {
    "index": i++,
    "tags": ['Best Sell', 'Discount'],
    "categories": ['laptop'],
    "discount": 10,
    "img_url": products.laptop1,
    "name": "Laptop ASUS Computer",
    "brand": "ASUS",
    "model": "ASUS Laptop",
    "stars": 4,
    "reviews": 550,
    "price_usd": 1199.99,
    "ship_to_country": "Egypt"
  },
  {
    "index": i++,
    "tags": ['New', 'Discount'],
    "categories": ['pc'],
    "discount": 10,
    "img_url": products.pc1,
    "name": "Megaport PC Gamer AMD FX-6100",
    "brand": "Megaport",
    "model": "PC Gamer AMD FX-6100",
    "stars": 4.5, 
    "reviews": 700,
    "price_usd": 820.99,
    "ship_to_country": "United States"
  },
  {
    "index": i++,
    "tags": ['Best Sell', 'Discount'],
    "categories": ['laptop'],
    "discount": 25,
    "img_url": products.laptop2,
    "name": "Xiaomi Mi Notebook Air 12.5″ Laptop",
    "brand": "Xiaomi",
    "model": "Mi Notebook Air",
    "stars": 4.5,
    "reviews": 700,
    "price_usd": 1005,
    "ship_to_country": "Egypt"
  },
  {
    "index": i++,
    "tags": [],
    "categories": ['phone'],
    "discount": 25,
    "img_url": products.mobile2,
    "name": "Xiaomi Mi Notebook Air 12.5″ Laptop",
    "brand": "Xiaomi",
    "model": "Mi Notebook Air",
    "stars": 4,
    "reviews": 700,
    "price_usd": 432.99,
    "ship_to_country": "Egypt"
  },
  {
    "index": i++,
    "tags": ['Best Sell', 'Discount'],
    "categories": ['headphone'],
    "discount": 25,
    "img_url": products.headphone2,
    "name": "Headset Xbox 360 Headphones Gamer Wireles",
    "brand": "Dr.Dre",
    "model": "Headset Xbox 360",
    "stars": 4.5,
    "reviews": 1044,
    "price_usd": 949.99,
    "ship_to_country": "Egypt"
  },
  {
    "index": i++,
    "tags": ['Discount'],
    "categories": ['laptop'],
    "discount": 50,
    "img_url": products.laptop3,
    "name": "HP EliteBook Laptop Intel Core i5 Hewlett-Packard",
    "brand": "HP",
    "model": "HP Intel Core i5",
    "stars": 4.5,
    "reviews": 120,
    "price_usd": 799.99,
    "ship_to_country": "United States"
  },
  {
    "index": i++,
    "tags": ['Discount'],
    "categories": ['xbox'],
    "discount": 50,
    "img_url": products.xbox1,
    "name": "Sony PlayStation 5",
    "brand": "Sony",
    "model": "PlayStation 5",
    "stars": 2,
    "reviews": 200,
    "price_usd": 499.99,
    "ship_to_country": "United States"
  },
  {
    "index": i++,
    "tags": ['Best Sell'],
    "categories": ['laptop'],
    "discount": 50,
    "img_url": products.laptop4,
    "name": "Laptop Dell Computer HP Pavilion",
    "brand": "Dell",
    "model": "XPS 15",
    "stars": 3,
    "reviews": 80,
    "price_usd": 1299.99,
    "ship_to_country": "United States"
  },
  {
    "index": i++,
    "tags": [],
    "categories": ['camera'],
    "discount": 0,
    "img_url": products.camera4,
    "name": "Canon EOS Rebel T7i DSLR Camera",
    "brand": "Canon",
    "model": "EOS Rebel T7i",
    "stars": 2.5,
    "reviews": 60,
    "price_usd": 699.99,
    "ship_to_country": "United States"
  },
  {
    "index": i++,
    "tags": ['Best Sell'],
    "categories": ['headphone'],
    "discount": 0,
    "img_url": products.headphone3,
    "name": "Bose QuietComfort 35 II Headphones",
    "brand": "Bose",
    "model": "QuietComfort 35 II",
    "stars": 4,
    "reviews": 40,
    "price_usd": 299.99,
    "ship_to_country": "United States"
  },
    {
      "index": i++,
      "tags": [],
      "categories": ['camera'],
      "discount": 25,
      "img_url": products.camera1,
      "name": "Canon EOS 5D Mark III",
      "brand": "Canon",
      "model": "EOS 5D Mark III",
      "stars": 4.5, 
      "reviews": 80,
      "price_usd": 1799.99,
      "ship_to_country": "United States"
    },
    {
      "index": i++,
      "tags": [],
      "categories": ['camera'],
      "discount": 0,
      "img_url": products.camera2,
      "name": "Nikon DSLR camera with flash",
      "brand": "Nikon",
      "model": "DSLR camera with flash",
      "stars": 3,
      "reviews": 550,
      "price_usd": 1122.85,
      "ship_to_country": "Egypt"
    },
    {
      "index": i++,
      "tags": ['Discount'],
      "categories": ['camera'],
      "discount": 50,
      "img_url": products.camera3,
      "name": "Sony camcorders Video Cameras",
      "brand": "Sony",
      "model": "Video Cameras",
      "stars": 4.5, 
      "reviews": 600,
      "price_usd": 899.99,
      "ship_to_country": "United States"
    },
    {
      "index": i++,
      "tags": ['New'],
      "categories": ['phone'],
      "discount": 0,
      "img_url": products.mobile1,
      "name": "Samsung 4G Smartphone",
      "brand": "Samsung",
      "model": "Galaxy S21",
      "stars": 4.5, 
      "reviews": 120,
      "price_usd": 755.99,
      "ship_to_country": "United States"
    },
    {
      "index": i++,
      "tags": ['New'],
      "categories": ['phone'],
      "discount": 0,
      "img_url": products.mobile3,
      "name": "iPhone 8 Plus, iPhone X, iPhone 7 Plus, Apple iPhone SE",
      "brand": "Apple",
      "model": "iPhone Series",
      "stars": 4.5, 
      "reviews": 100, 
      "price_usd": 993.99,
      "ship_to_country": "United States"
    },
  ];
  
